//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class edc_other_t
    {
        public int id { get; set; }
        public Nullable<System.Guid> loris_id { get; set; }
        public string ibso_id { get; set; }
        public string path_edc { get; set; }
        public int type { get; set; }
        public int state { get; set; }
        public Nullable<System.DateTime> uplodate_date { get; set; }
        public string bucket { get; set; }
        public string ros_client_id { get; set; }
        public string ros_contract_number { get; set; }
    }
}
