//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class edc_other_files
    {
        public long id { get; set; }
        public string s3id { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string path_edc { get; set; }
        public string path_edc_file { get; set; }
        public string filename { get; set; }
        public Nullable<double> size { get; set; }
        public string md5 { get; set; }
        public Nullable<int> upload_succes { get; set; }
        public string error { get; set; }
        public Nullable<int> state { get; set; }
        public string actual_for_process { get; set; }
        public Nullable<int> ede_other_t_id { get; set; }
        public string tecmid { get; set; }
        public string tem_filename { get; set; }
        public string extension { get; set; }
        public string tecmid2 { get; set; }
    }
}
